### ISSUE TITLE
Add haptic feedback when export finishes

### ISSUE THREAD

**Issue by aheze** [aheze/ProgressGif#4]
Currently, this is what happens when export finishes:
<image src="https://raw.githubusercontent.com/aheze/ProgressGif/main/Assets/GitHub/Issues/1DD30080-607C-46D4-8721-EB02927491A5.gif" width="300">
It would be nice to have a haptic *click* when the `Export` button pops up!

[Relavent file](https://github.com/aheze/ProgressGif/blob/968877acd13be84f4386861512907ce89ee44ddf/ProgressGif/Editing/Base%20Editing/Rendering/ExportViewController.swift#L244), what to edit:
```
UIView.animate(withDuration: 0.6, animations: {
    self.processingLabel.alpha = 1
    self.imageView.alpha = 1
})

/// Add haptic code here!

self.exportButton.transform = CGAffineTransform(scaleX: 0.8, y: 0.8)
UIView.animate(withDuration: 1, delay: 0.4, usingSpringWithDamping: 0.9, initialSpringVelocity: 0.5, options: .curveLinear, animations: {
    self.exportButton.alpha = 1
    self.exportButton.transform = CGAffineTransform.identity
}, completion: nil)
```

**Comment by mcblooder** [comment]
#9 implemented here

**Comment by aheze** [comment]
Thanks @mcblooder!

**Comment by aheze** [comment]
@mcblooder, want to add yourself to the contributors page in the app?
https://github.com/aheze/ProgressGif/blob/a3eb1f0c88ea5b55f862301f79289171663ee4d3/ProgressGif/About/Contributors.swift#L81
```swift
let aheze = Contributor()
aheze.name = "Zheng"
aheze.additions = 199405
aheze.deletions = 29470
aheze.profileName = "ahezeProfile" /// name of your profile pic, add it to `Contributing.xcassets`
aheze.linkImageName = "Medium"
if let profileURL = URL(string: "https://medium.com/@ahzzheng") {
    aheze.link = profileURL
}
contributors.append(aheze)
```

**Comment by mcblooder** [comment]
@aheze nah, thanks, I'm good 👍 
Happy to help ya :)
