### ISSUE TITLE
Display Gif size when export finishes

### ISSUE THREAD

**Issue by aheze** [aheze/ProgressGif#5]
When the export finishes, you don't know how big the file is.
<image src="https://raw.githubusercontent.com/aheze/ProgressGif/main/Assets/GitHub/Issues/1DD30080-607C-46D4-8721-EB02927491A5.gif" width="300">

The "Export!" button should say the file size. Something like "Export! (10mb)" would work!

Currently you can get the file size (already formatted) like this:
```
let fileSize = exportedGifURL.fileSizeString
print("fileSize: \(fileSize)")
```

[Relevant file](https://github.com/aheze/ProgressGif/blob/968877acd13be84f4386861512907ce89ee44ddf/ProgressGif/Editing/Base%20Editing/Rendering/ExportViewController.swift#L244), what to edit:
```
UIView.animate(withDuration: 0.6, animations: {
    self.processingLabel.alpha = 1
    self.imageView.alpha = 1
})

/// set `self.exportButton`'s title here (add the file size)

self.exportButton.transform = CGAffineTransform(scaleX: 0.8, y: 0.8)
UIView.animate(withDuration: 1, delay: 0.4, usingSpringWithDamping: 0.9, initialSpringVelocity: 0.5, options: .curveLinear, animations: {
    self.exportButton.alpha = 1
    self.exportButton.transform = CGAffineTransform.identity
}, completion: nil)
```

**Comment by AyonPal** [comment]
I want to try this.

**Comment by aheze** [comment]
Thanks @janakmshah!

**Comment by aheze** [comment]
@janakmshah, want to add yourself to the contributors page in the app?
https://github.com/aheze/ProgressGif/blob/a3eb1f0c88ea5b55f862301f79289171663ee4d3/ProgressGif/About/Contributors.swift#L81
```swift
let aheze = Contributor()
aheze.name = "Zheng"
aheze.additions = 199405
aheze.deletions = 29470
aheze.profileName = "ahezeProfile" /// name of your profile pic, add it to `Contributing.xcassets`
aheze.linkImageName = "Medium"
if let profileURL = URL(string: "https://medium.com/@ahzzheng") {
    aheze.link = profileURL
}
contributors.append(aheze)
```

**Comment by janakmshah** [comment]
Thanks @aheze, have opened a PR :)
https://github.com/aheze/ProgressGif/pull/17
