### ISSUE TITLE
Make dark mode look better

### ISSUE THREAD

**Issue by aheze** [aheze/ProgressGif#6]
Currently the steppers look pretty... not good-looking 😅
Exhibit 1 | Exhibit 2 | Exhibit 3
--- | --- | ---
![](https://raw.githubusercontent.com/aheze/ProgressGif/main/Assets/GitHub/Issues/IMG_7302.PNG) | ![](https://raw.githubusercontent.com/aheze/ProgressGif/main/Assets/GitHub/Issues/IMG_7303.PNG) | ![](https://raw.githubusercontent.com/aheze/ProgressGif/main/Assets/GitHub/Issues/IMG_7304.PNG)

It's a weird poop color. Anyone got a better color palette?
Inside [Assets.xcassets](https://github.com/aheze/ProgressGif/tree/main/ProgressGif/Assets.xcassets):
![](https://raw.githubusercontent.com/aheze/ProgressGif/main/Assets/GitHub/Issues/Shot%202020-10-05%20at%207.29.26%20PM.png)

**Comment by thejayhaykid** [comment]
I can take this one

**Comment by aheze** [comment]
Awesome, thanks!

**Comment by thejayhaykid** [comment]
How much of the current color palette are you looking to keep? Do you want to keep it yellow? Or just anything aesthetically pleasing?

**Comment by aheze** [comment]
Try to stick with the current logo colors -- something along yellow, orange, or pink. 
![](https://raw.githubusercontent.com/aheze/ProgressGif/main/Assets/GitHub/Logo/LogoWithText.png)

**Comment by aheze** [comment]
[Closed!](https://github.com/aheze/ProgressGif/pull/11)
